language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libvte-dev alex happy
  - cabal install Cabal
  - cabal install cabal-install
install:
  - PATH="$HOME/.cabal/bin:$PATH" cabal install gtk2hs-buildtools
script:
  - PATH="$HOME/.cabal/bin:$PATH" cabal install
notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
  email: true
