env:
 - CABALVER=1.24 GHCVER=7.8.3
 - CABALVER=1.24 GHCVER=7.8.4
 - CABALVER=1.24 GHCVER=7.10.1
 - CABALVER=1.24 GHCVER=7.10.2
 - CABALVER=1.24 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get --no-install-recommends install libvte-dev libvte-2.90-dev
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ] || [ ${GHCVER%.*} = "8.0" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal update
 - cabal install Cabal
 - cabal install gtk2hs-buildtools

script:
  - ./install-both.sh

notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
  email: true
